spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8882
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8882/auth/realms/loove